### ISSUE TITLE
Error with getting current battery...

### ISSUE THREAD

**Issue by malleralle** [AchimPieters/Apple-Homebridge-Door-Lock#1]
Hi,

first of all: Great work! Thank you! 

I made a similar hardware setup with esp8266. Unfortunately I get an error when running homebridge:

First everything is running fine and I can see a lock accessory in the Home-app on iOS.
But after a while I get this error in the command window:

>[2017-07-30 15:41:35] [Haustür] Getting current state...
>[2017-07-30 15:41:35] [Haustür] Getting current state...
>[2017-07-30 15:41:36] [Haustür] Getting current battery...
>/usr/lib/node_modules/homebridge-lock/index.js:62
>            this.log("Error getting state (status code %s): %s", response.statusCode, err);
>                                                                         ^
>
>TypeError: Cannot read property 'statusCode' of undefined
>    at LockAccessory.<anonymous> (/usr/lib/node_modules/homebridge-lock/index.js:62:74)
>    at self.callback (/usr/lib/node_modules/homebridge-lock/node_modules/request/request.js:373:22)
>    at emitOne (events.js:96:13)
>    at Request.emit (events.js:188:7)
>    at Request.onRequestError (/usr/lib/node_modules/homebridge-lock/node_modules/request/request.js:971:8)
>    at emitOne (events.js:96:13)
>    at ClientRequest.emit (events.js:188:7)
>    at Socket.socketErrorListener (_http_client.js:309:9)
>    at emitOne (events.js:96:13)
>    at Socket.emit (events.js:188:7)

Do you know a solution for this?

**Comment by AchimPieters** [comment]
@malleralle 

I think I have the solution for you. In one of my previous projects (https://www.studiopieters.nl/apple-homebridge-neopixel-light/) I had a similar problem.

It is key that you have a stable power supply!! with suitable capacitors. If you power supply isn't stable it will cause al kind of trouble, because your ESP8266 will crash.

Here's  a website with more information: https://internetofhomethings.com/homethings/?p=396

**Comment by malleralle** [comment]
@AchimPieters 
Got it to work!
